### ISSUE TITLE
Shirt Shop

### ISSUE THREAD

**Issue by cl1sman** [cl1sman/Object-Oriented-Programming-OOP#6]
Nessa atividade você construirá um sistema orientado a objetos da startup de camisetas ShirtShop.
Uma camiseta é identificada pelo tamanho (que pode ser P, M, G ou GG), cor, se possui ou não estampa, preço de custo e preço de venda. Uma camiseta possui um dono, que é identificado pelo nome completo, cpf e data de nascimento. Como nossa startup ainda está em fase embrionária, no momento um dono de camisetas pode possuir no máximo duas camisetas da ShirtShop.

Modele o cenário acima utilizando orientação a objetos. Após a construção das classes, construa um programa que cria 6 camisetas (podem ter informações fixas) e 3 possíveis donos de camisetas (também com informações fixas). Após a criação das camisetas e dos donos, atribua cada camiseta a um dono. Por fim, seu sistema deve imprimir as informações pessoais de cada dono, em conjunto com as informações das camisetas que ele possui.

Envie todas as classes Java construídas para a solução desse exercício.

### To-Do
**Classe Camiseta**
- [x] tamanho
- [x] cor
- [x] estampa
- [x] preço de custo
- [x] preço de venda
- [x] Uma camiseta possui um dono, que é identificado pelo nome completo, cpf e data de nascimento

**Classe Pessoa**
- [x] nome completo, 
- [x] cpf e 
- [x] data de nascimento
- [x] um dono de camisetas pode possuir no máximo duas camisetas da ShirtShop.

**Program**
- [x] construa um programa que cria 6 camisetas (podem ter informações fixas) e 
- [x] 3 possíveis donos de camisetas (também com informações fixas)
- [x] Após a criação das camisetas e dos donos, atribua cada camiseta a um dono
- [x] Por fim, seu sistema deve imprimir as informações pessoais de cada dono, em conjunto com as informações das camisetas que ele possui.
